/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#include "cell_handovers_list.h"
#include "all_handovers.h"

// namespace ns3{
// namespace ric_control {

asn_TYPE_member_t asn_MBR_AllHandoversList_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CellHandoverList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellHandoverList"
		},
};
static const ber_tlv_tag_t asn_DEF_AllHandoversList_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_AllHandoversList_specs_1 = {
	sizeof(struct AllHandoversList),
	offsetof(struct AllHandoversList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_AllHandoversList = {
	"AllHandoversList",
	"AllHandoversList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_AllHandoversList_tags_1,
	sizeof(asn_DEF_AllHandoversList_tags_1)
		/sizeof(asn_DEF_AllHandoversList_tags_1[0]), /* 1 */
	asn_DEF_AllHandoversList_tags_1,	/* Same as above */
	sizeof(asn_DEF_AllHandoversList_tags_1)
		/sizeof(asn_DEF_AllHandoversList_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_AllHandoversList_1,
	1,	/* Single element */
	&asn_SPC_AllHandoversList_specs_1	/* Additional specs */
};

// }
// }

