

/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_ALL_HANDOVERS_PLMN_H_
#define	_ALL_HANDOVERS_PLMN_H_


#include <asn_application.h>

/* Including external dependencies */
// #include <asn_SEQUENCE.h>

#include "PLMN-Identity.h"
#include <constr_SEQUENCE.h>
#include "all_handovers.h"


#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
// struct AllHandoversList;

typedef struct AllHandoversListPlmn {
	PLMN_Identity_t plmn_id;
	AllHandoversList_t* allHandoversList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AllHandoversListPlmn_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AllHandoversListPlmn;
// extern asn_SET_OF_specifics_t asn_SPC_AllHandoversList_specs_1;
extern asn_SEQUENCE_specifics_t asn_SPC_AllHandoversListPlmn_specs_1;
extern asn_TYPE_member_t asn_MBR_AllHandoversListPlmn_1[2];
extern asn_per_constraints_t asn_PER_type_AllHandoversListPlmn_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ALL_HANDOVERS_PLMN_H_ */
#include <asn_internal.h>
