/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#include "handover_list.h"
#include "handover_item.h"

#include <asn_application.h>
#include <per_support.h>
namespace ns3{
namespace ric_control {

asn_per_constraints_t asn_PER_type_CellHandoverItemList_constr_1 CC_NOTUSED = {
	{ asn_per_constraint_s::APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ asn_per_constraint_s::APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};

asn_TYPE_member_t asn_MBR_CellHandoverItemList_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CellHandoverItem,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_CellHandoverItemList_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_CellHandoverItemList_specs_1 = {
	sizeof(struct CellHandoverItemList),
	offsetof(struct CellHandoverItemList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_CellHandoverItemList = {
	"CellHandoverItemList",
	"CellHandoverItemList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_CellHandoverItemList_tags_1,
	sizeof(asn_DEF_CellHandoverItemList_tags_1)
		/sizeof(asn_DEF_CellHandoverItemList_tags_1[0]), /* 1 */
	asn_DEF_CellHandoverItemList_tags_1,	/* Same as above */
	sizeof(asn_DEF_CellHandoverItemList_tags_1)
		/sizeof(asn_DEF_CellHandoverItemList_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_CellHandoverItemList_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_CellHandoverItemList_1,
	1,	/* Single element */
	&asn_SPC_CellHandoverItemList_specs_1	/* Additional specs */
};

}
}
