/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "E2SM-KPM-v02.00.03.asn"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example -D E2SM-KPM-v02.00.03`
 */

#ifndef	_Handover_H_
#define	_Handover_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellHandoverItem;

/* MeasurementRecord */
typedef struct Handover {
	A_SEQUENCE_OF(struct CellHandoverItem) list;

    long sourceCellId;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Handover_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Handover;
extern asn_SET_OF_specifics_t asn_SPC_Handover_specs_1;
extern asn_TYPE_member_t asn_MBR_Handover_1[1];
extern asn_per_constraints_t asn_PER_type_Handover_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Handover_H_ */
#include <asn_internal.h>
